/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
)

// checks if the BulkDeleteTasksRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkDeleteTasksRequest{}

// BulkDeleteTasksRequest Either populate `taskIds` (with optional parallel `accountIds`) for multi-task delete, or `taskId` (with optional `accountId`) for the single-task fallback. `taskIds` wins when both are set. 
type BulkDeleteTasksRequest struct {
	TaskIds []string `json:"taskIds,omitempty"`
	// Parallel slice with taskIds — accountIds[i] targets taskIds[i].
	AccountIds []string `json:"accountIds,omitempty"`
	// Singular fallback when only deleting one task.
	TaskId *string `json:"taskId,omitempty"`
	AccountId *string `json:"accountId,omitempty"`
}

// NewBulkDeleteTasksRequest instantiates a new BulkDeleteTasksRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkDeleteTasksRequest() *BulkDeleteTasksRequest {
	this := BulkDeleteTasksRequest{}
	return &this
}

// NewBulkDeleteTasksRequestWithDefaults instantiates a new BulkDeleteTasksRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkDeleteTasksRequestWithDefaults() *BulkDeleteTasksRequest {
	this := BulkDeleteTasksRequest{}
	return &this
}

// GetTaskIds returns the TaskIds field value if set, zero value otherwise.
func (o *BulkDeleteTasksRequest) GetTaskIds() []string {
	if o == nil || IsNil(o.TaskIds) {
		var ret []string
		return ret
	}
	return o.TaskIds
}

// GetTaskIdsOk returns a tuple with the TaskIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDeleteTasksRequest) GetTaskIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.TaskIds) {
		return nil, false
	}
	return o.TaskIds, true
}

// HasTaskIds returns a boolean if a field has been set.
func (o *BulkDeleteTasksRequest) HasTaskIds() bool {
	if o != nil && !IsNil(o.TaskIds) {
		return true
	}

	return false
}

// SetTaskIds gets a reference to the given []string and assigns it to the TaskIds field.
func (o *BulkDeleteTasksRequest) SetTaskIds(v []string) {
	o.TaskIds = v
}

// GetAccountIds returns the AccountIds field value if set, zero value otherwise.
func (o *BulkDeleteTasksRequest) GetAccountIds() []string {
	if o == nil || IsNil(o.AccountIds) {
		var ret []string
		return ret
	}
	return o.AccountIds
}

// GetAccountIdsOk returns a tuple with the AccountIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDeleteTasksRequest) GetAccountIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AccountIds) {
		return nil, false
	}
	return o.AccountIds, true
}

// HasAccountIds returns a boolean if a field has been set.
func (o *BulkDeleteTasksRequest) HasAccountIds() bool {
	if o != nil && !IsNil(o.AccountIds) {
		return true
	}

	return false
}

// SetAccountIds gets a reference to the given []string and assigns it to the AccountIds field.
func (o *BulkDeleteTasksRequest) SetAccountIds(v []string) {
	o.AccountIds = v
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *BulkDeleteTasksRequest) GetTaskId() string {
	if o == nil || IsNil(o.TaskId) {
		var ret string
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDeleteTasksRequest) GetTaskIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskId) {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *BulkDeleteTasksRequest) HasTaskId() bool {
	if o != nil && !IsNil(o.TaskId) {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given string and assigns it to the TaskId field.
func (o *BulkDeleteTasksRequest) SetTaskId(v string) {
	o.TaskId = &v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *BulkDeleteTasksRequest) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDeleteTasksRequest) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *BulkDeleteTasksRequest) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *BulkDeleteTasksRequest) SetAccountId(v string) {
	o.AccountId = &v
}

func (o BulkDeleteTasksRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkDeleteTasksRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TaskIds) {
		toSerialize["taskIds"] = o.TaskIds
	}
	if !IsNil(o.AccountIds) {
		toSerialize["accountIds"] = o.AccountIds
	}
	if !IsNil(o.TaskId) {
		toSerialize["taskId"] = o.TaskId
	}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	return toSerialize, nil
}

type NullableBulkDeleteTasksRequest struct {
	value *BulkDeleteTasksRequest
	isSet bool
}

func (v NullableBulkDeleteTasksRequest) Get() *BulkDeleteTasksRequest {
	return v.value
}

func (v *NullableBulkDeleteTasksRequest) Set(val *BulkDeleteTasksRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeleteTasksRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeleteTasksRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeleteTasksRequest(val *BulkDeleteTasksRequest) *NullableBulkDeleteTasksRequest {
	return &NullableBulkDeleteTasksRequest{value: val, isSet: true}
}

func (v NullableBulkDeleteTasksRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeleteTasksRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


