/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
)

// checks if the DMReactionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DMReactionResponse{}

// DMReactionResponse `reactions` shape is provider-specific; treat as opaque.
type DMReactionResponse struct {
	// Updated reaction list for the message.
	Reactions interface{} `json:"reactions,omitempty"`
}

// NewDMReactionResponse instantiates a new DMReactionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDMReactionResponse() *DMReactionResponse {
	this := DMReactionResponse{}
	return &this
}

// NewDMReactionResponseWithDefaults instantiates a new DMReactionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDMReactionResponseWithDefaults() *DMReactionResponse {
	this := DMReactionResponse{}
	return &this
}

// GetReactions returns the Reactions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DMReactionResponse) GetReactions() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Reactions
}

// GetReactionsOk returns a tuple with the Reactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DMReactionResponse) GetReactionsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Reactions) {
		return nil, false
	}
	return &o.Reactions, true
}

// HasReactions returns a boolean if a field has been set.
func (o *DMReactionResponse) HasReactions() bool {
	if o != nil && !IsNil(o.Reactions) {
		return true
	}

	return false
}

// SetReactions gets a reference to the given interface{} and assigns it to the Reactions field.
func (o *DMReactionResponse) SetReactions(v interface{}) {
	o.Reactions = v
}

func (o DMReactionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DMReactionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Reactions != nil {
		toSerialize["reactions"] = o.Reactions
	}
	return toSerialize, nil
}

type NullableDMReactionResponse struct {
	value *DMReactionResponse
	isSet bool
}

func (v NullableDMReactionResponse) Get() *DMReactionResponse {
	return v.value
}

func (v *NullableDMReactionResponse) Set(val *DMReactionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDMReactionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDMReactionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDMReactionResponse(val *DMReactionResponse) *NullableDMReactionResponse {
	return &NullableDMReactionResponse{value: val, isSet: true}
}

func (v NullableDMReactionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDMReactionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


