/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Cell type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Cell{}

// Cell A single cell. `value` is the JSON-serializable cell contents; interpretation is provider-specific. 
type Cell struct {
	Row int32 `json:"row"`
	Column string `json:"column"`
	// Any JSON value (string, number, boolean, null, object).
	Value interface{} `json:"value"`
}

type _Cell Cell

// NewCell instantiates a new Cell object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCell(row int32, column string, value interface{}) *Cell {
	this := Cell{}
	this.Row = row
	this.Column = column
	this.Value = value
	return &this
}

// NewCellWithDefaults instantiates a new Cell object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCellWithDefaults() *Cell {
	this := Cell{}
	return &this
}

// GetRow returns the Row field value
func (o *Cell) GetRow() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Row
}

// GetRowOk returns a tuple with the Row field value
// and a boolean to check if the value has been set.
func (o *Cell) GetRowOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Row, true
}

// SetRow sets field value
func (o *Cell) SetRow(v int32) {
	o.Row = v
}

// GetColumn returns the Column field value
func (o *Cell) GetColumn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Column
}

// GetColumnOk returns a tuple with the Column field value
// and a boolean to check if the value has been set.
func (o *Cell) GetColumnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Column, true
}

// SetColumn sets field value
func (o *Cell) SetColumn(v string) {
	o.Column = v
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *Cell) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Cell) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Cell) SetValue(v interface{}) {
	o.Value = v
}

func (o Cell) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Cell) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["row"] = o.Row
	toSerialize["column"] = o.Column
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

func (o *Cell) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"row",
		"column",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCell := _Cell{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCell)

	if err != nil {
		return err
	}

	*o = Cell(varCell)

	return err
}

type NullableCell struct {
	value *Cell
	isSet bool
}

func (v NullableCell) Get() *Cell {
	return v.value
}

func (v *NullableCell) Set(val *Cell) {
	v.value = val
	v.isSet = true
}

func (v NullableCell) IsSet() bool {
	return v.isSet
}

func (v *NullableCell) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCell(val *Cell) *NullableCell {
	return &NullableCell{value: val, isSet: true}
}

func (v NullableCell) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCell) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


