/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateRecordTypeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRecordTypeRequest{}

// CreateRecordTypeRequest struct for CreateRecordTypeRequest
type CreateRecordTypeRequest struct {
	OrganizationId *string `json:"organization_id,omitempty"`
	Slug *string `json:"slug,omitempty"`
	Name string `json:"name"`
	NamePlural *string `json:"name_plural,omitempty"`
	Icon *string `json:"icon,omitempty"`
	AttributeSchema []map[string]interface{} `json:"attribute_schema,omitempty"`
}

type _CreateRecordTypeRequest CreateRecordTypeRequest

// NewCreateRecordTypeRequest instantiates a new CreateRecordTypeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRecordTypeRequest(name string) *CreateRecordTypeRequest {
	this := CreateRecordTypeRequest{}
	this.Name = name
	return &this
}

// NewCreateRecordTypeRequestWithDefaults instantiates a new CreateRecordTypeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRecordTypeRequestWithDefaults() *CreateRecordTypeRequest {
	this := CreateRecordTypeRequest{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *CreateRecordTypeRequest) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecordTypeRequest) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *CreateRecordTypeRequest) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *CreateRecordTypeRequest) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *CreateRecordTypeRequest) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecordTypeRequest) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *CreateRecordTypeRequest) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *CreateRecordTypeRequest) SetSlug(v string) {
	o.Slug = &v
}

// GetName returns the Name field value
func (o *CreateRecordTypeRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateRecordTypeRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateRecordTypeRequest) SetName(v string) {
	o.Name = v
}

// GetNamePlural returns the NamePlural field value if set, zero value otherwise.
func (o *CreateRecordTypeRequest) GetNamePlural() string {
	if o == nil || IsNil(o.NamePlural) {
		var ret string
		return ret
	}
	return *o.NamePlural
}

// GetNamePluralOk returns a tuple with the NamePlural field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecordTypeRequest) GetNamePluralOk() (*string, bool) {
	if o == nil || IsNil(o.NamePlural) {
		return nil, false
	}
	return o.NamePlural, true
}

// HasNamePlural returns a boolean if a field has been set.
func (o *CreateRecordTypeRequest) HasNamePlural() bool {
	if o != nil && !IsNil(o.NamePlural) {
		return true
	}

	return false
}

// SetNamePlural gets a reference to the given string and assigns it to the NamePlural field.
func (o *CreateRecordTypeRequest) SetNamePlural(v string) {
	o.NamePlural = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *CreateRecordTypeRequest) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecordTypeRequest) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *CreateRecordTypeRequest) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *CreateRecordTypeRequest) SetIcon(v string) {
	o.Icon = &v
}

// GetAttributeSchema returns the AttributeSchema field value if set, zero value otherwise.
func (o *CreateRecordTypeRequest) GetAttributeSchema() []map[string]interface{} {
	if o == nil || IsNil(o.AttributeSchema) {
		var ret []map[string]interface{}
		return ret
	}
	return o.AttributeSchema
}

// GetAttributeSchemaOk returns a tuple with the AttributeSchema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecordTypeRequest) GetAttributeSchemaOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.AttributeSchema) {
		return nil, false
	}
	return o.AttributeSchema, true
}

// HasAttributeSchema returns a boolean if a field has been set.
func (o *CreateRecordTypeRequest) HasAttributeSchema() bool {
	if o != nil && !IsNil(o.AttributeSchema) {
		return true
	}

	return false
}

// SetAttributeSchema gets a reference to the given []map[string]interface{} and assigns it to the AttributeSchema field.
func (o *CreateRecordTypeRequest) SetAttributeSchema(v []map[string]interface{}) {
	o.AttributeSchema = v
}

func (o CreateRecordTypeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRecordTypeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.NamePlural) {
		toSerialize["name_plural"] = o.NamePlural
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.AttributeSchema) {
		toSerialize["attribute_schema"] = o.AttributeSchema
	}
	return toSerialize, nil
}

func (o *CreateRecordTypeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRecordTypeRequest := _CreateRecordTypeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRecordTypeRequest)

	if err != nil {
		return err
	}

	*o = CreateRecordTypeRequest(varCreateRecordTypeRequest)

	return err
}

type NullableCreateRecordTypeRequest struct {
	value *CreateRecordTypeRequest
	isSet bool
}

func (v NullableCreateRecordTypeRequest) Get() *CreateRecordTypeRequest {
	return v.value
}

func (v *NullableCreateRecordTypeRequest) Set(val *CreateRecordTypeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRecordTypeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRecordTypeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRecordTypeRequest(val *CreateRecordTypeRequest) *NullableCreateRecordTypeRequest {
	return &NullableCreateRecordTypeRequest{value: val, isSet: true}
}

func (v NullableCreateRecordTypeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRecordTypeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


