/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSheetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSheetRequest{}

// CreateSheetRequest struct for CreateSheetRequest
type CreateSheetRequest struct {
	Name string `json:"name"`
	Description NullableString `json:"description,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`
	RowCount *int32 `json:"rowCount,omitempty"`
	ColumnCount *int32 `json:"columnCount,omitempty"`
	// Optional override for the target connected account. May also be passed as `?accountId=`. 
	AccountId *string `json:"accountId,omitempty"`
	Provider *string `json:"provider,omitempty"`
}

type _CreateSheetRequest CreateSheetRequest

// NewCreateSheetRequest instantiates a new CreateSheetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSheetRequest(name string) *CreateSheetRequest {
	this := CreateSheetRequest{}
	this.Name = name
	return &this
}

// NewCreateSheetRequestWithDefaults instantiates a new CreateSheetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSheetRequestWithDefaults() *CreateSheetRequest {
	this := CreateSheetRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateSheetRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSheetRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSheetRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateSheetRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateSheetRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateSheetRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CreateSheetRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CreateSheetRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CreateSheetRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateSheetRequest) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSheetRequest) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateSheetRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *CreateSheetRequest) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetRowCount returns the RowCount field value if set, zero value otherwise.
func (o *CreateSheetRequest) GetRowCount() int32 {
	if o == nil || IsNil(o.RowCount) {
		var ret int32
		return ret
	}
	return *o.RowCount
}

// GetRowCountOk returns a tuple with the RowCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSheetRequest) GetRowCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RowCount) {
		return nil, false
	}
	return o.RowCount, true
}

// HasRowCount returns a boolean if a field has been set.
func (o *CreateSheetRequest) HasRowCount() bool {
	if o != nil && !IsNil(o.RowCount) {
		return true
	}

	return false
}

// SetRowCount gets a reference to the given int32 and assigns it to the RowCount field.
func (o *CreateSheetRequest) SetRowCount(v int32) {
	o.RowCount = &v
}

// GetColumnCount returns the ColumnCount field value if set, zero value otherwise.
func (o *CreateSheetRequest) GetColumnCount() int32 {
	if o == nil || IsNil(o.ColumnCount) {
		var ret int32
		return ret
	}
	return *o.ColumnCount
}

// GetColumnCountOk returns a tuple with the ColumnCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSheetRequest) GetColumnCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ColumnCount) {
		return nil, false
	}
	return o.ColumnCount, true
}

// HasColumnCount returns a boolean if a field has been set.
func (o *CreateSheetRequest) HasColumnCount() bool {
	if o != nil && !IsNil(o.ColumnCount) {
		return true
	}

	return false
}

// SetColumnCount gets a reference to the given int32 and assigns it to the ColumnCount field.
func (o *CreateSheetRequest) SetColumnCount(v int32) {
	o.ColumnCount = &v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *CreateSheetRequest) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSheetRequest) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *CreateSheetRequest) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *CreateSheetRequest) SetAccountId(v string) {
	o.AccountId = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *CreateSheetRequest) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSheetRequest) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *CreateSheetRequest) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *CreateSheetRequest) SetProvider(v string) {
	o.Provider = &v
}

func (o CreateSheetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSheetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.RowCount) {
		toSerialize["rowCount"] = o.RowCount
	}
	if !IsNil(o.ColumnCount) {
		toSerialize["columnCount"] = o.ColumnCount
	}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	return toSerialize, nil
}

func (o *CreateSheetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSheetRequest := _CreateSheetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSheetRequest)

	if err != nil {
		return err
	}

	*o = CreateSheetRequest(varCreateSheetRequest)

	return err
}

type NullableCreateSheetRequest struct {
	value *CreateSheetRequest
	isSet bool
}

func (v NullableCreateSheetRequest) Get() *CreateSheetRequest {
	return v.value
}

func (v *NullableCreateSheetRequest) Set(val *CreateSheetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSheetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSheetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSheetRequest(val *CreateSheetRequest) *NullableCreateSheetRequest {
	return &NullableCreateSheetRequest{value: val, isSet: true}
}

func (v NullableCreateSheetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSheetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


