/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppFileContentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppFileContentResponse{}

// AppFileContentResponse struct for AppFileContentResponse
type AppFileContentResponse struct {
	Path string `json:"path"`
	Content *string `json:"content,omitempty"`
}

type _AppFileContentResponse AppFileContentResponse

// NewAppFileContentResponse instantiates a new AppFileContentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppFileContentResponse(path string) *AppFileContentResponse {
	this := AppFileContentResponse{}
	this.Path = path
	return &this
}

// NewAppFileContentResponseWithDefaults instantiates a new AppFileContentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppFileContentResponseWithDefaults() *AppFileContentResponse {
	this := AppFileContentResponse{}
	return &this
}

// GetPath returns the Path field value
func (o *AppFileContentResponse) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *AppFileContentResponse) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *AppFileContentResponse) SetPath(v string) {
	o.Path = v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *AppFileContentResponse) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppFileContentResponse) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *AppFileContentResponse) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *AppFileContentResponse) SetContent(v string) {
	o.Content = &v
}

func (o AppFileContentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppFileContentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["path"] = o.Path
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	return toSerialize, nil
}

func (o *AppFileContentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppFileContentResponse := _AppFileContentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppFileContentResponse)

	if err != nil {
		return err
	}

	*o = AppFileContentResponse(varAppFileContentResponse)

	return err
}

type NullableAppFileContentResponse struct {
	value *AppFileContentResponse
	isSet bool
}

func (v NullableAppFileContentResponse) Get() *AppFileContentResponse {
	return v.value
}

func (v *NullableAppFileContentResponse) Set(val *AppFileContentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAppFileContentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAppFileContentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppFileContentResponse(val *AppFileContentResponse) *NullableAppFileContentResponse {
	return &NullableAppFileContentResponse{value: val, isSet: true}
}

func (v NullableAppFileContentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppFileContentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


