/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkFilesResponseFailedInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkFilesResponseFailedInner{}

// BulkFilesResponseFailedInner struct for BulkFilesResponseFailedInner
type BulkFilesResponseFailedInner struct {
	FileId string `json:"fileId"`
	Error string `json:"error"`
}

type _BulkFilesResponseFailedInner BulkFilesResponseFailedInner

// NewBulkFilesResponseFailedInner instantiates a new BulkFilesResponseFailedInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkFilesResponseFailedInner(fileId string, error_ string) *BulkFilesResponseFailedInner {
	this := BulkFilesResponseFailedInner{}
	this.FileId = fileId
	this.Error = error_
	return &this
}

// NewBulkFilesResponseFailedInnerWithDefaults instantiates a new BulkFilesResponseFailedInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkFilesResponseFailedInnerWithDefaults() *BulkFilesResponseFailedInner {
	this := BulkFilesResponseFailedInner{}
	return &this
}

// GetFileId returns the FileId field value
func (o *BulkFilesResponseFailedInner) GetFileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value
// and a boolean to check if the value has been set.
func (o *BulkFilesResponseFailedInner) GetFileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileId, true
}

// SetFileId sets field value
func (o *BulkFilesResponseFailedInner) SetFileId(v string) {
	o.FileId = v
}

// GetError returns the Error field value
func (o *BulkFilesResponseFailedInner) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *BulkFilesResponseFailedInner) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *BulkFilesResponseFailedInner) SetError(v string) {
	o.Error = v
}

func (o BulkFilesResponseFailedInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkFilesResponseFailedInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fileId"] = o.FileId
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *BulkFilesResponseFailedInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fileId",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkFilesResponseFailedInner := _BulkFilesResponseFailedInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkFilesResponseFailedInner)

	if err != nil {
		return err
	}

	*o = BulkFilesResponseFailedInner(varBulkFilesResponseFailedInner)

	return err
}

type NullableBulkFilesResponseFailedInner struct {
	value *BulkFilesResponseFailedInner
	isSet bool
}

func (v NullableBulkFilesResponseFailedInner) Get() *BulkFilesResponseFailedInner {
	return v.value
}

func (v *NullableBulkFilesResponseFailedInner) Set(val *BulkFilesResponseFailedInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkFilesResponseFailedInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkFilesResponseFailedInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkFilesResponseFailedInner(val *BulkFilesResponseFailedInner) *NullableBulkFilesResponseFailedInner {
	return &NullableBulkFilesResponseFailedInner{value: val, isSet: true}
}

func (v NullableBulkFilesResponseFailedInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkFilesResponseFailedInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


