/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateRecommendationStatusRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateRecommendationStatusRequest{}

// UpdateRecommendationStatusRequest struct for UpdateRecommendationStatusRequest
type UpdateRecommendationStatusRequest struct {
	Status string `json:"status"`
}

type _UpdateRecommendationStatusRequest UpdateRecommendationStatusRequest

// NewUpdateRecommendationStatusRequest instantiates a new UpdateRecommendationStatusRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateRecommendationStatusRequest(status string) *UpdateRecommendationStatusRequest {
	this := UpdateRecommendationStatusRequest{}
	this.Status = status
	return &this
}

// NewUpdateRecommendationStatusRequestWithDefaults instantiates a new UpdateRecommendationStatusRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateRecommendationStatusRequestWithDefaults() *UpdateRecommendationStatusRequest {
	this := UpdateRecommendationStatusRequest{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateRecommendationStatusRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateRecommendationStatusRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateRecommendationStatusRequest) SetStatus(v string) {
	o.Status = v
}

func (o UpdateRecommendationStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateRecommendationStatusRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *UpdateRecommendationStatusRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateRecommendationStatusRequest := _UpdateRecommendationStatusRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateRecommendationStatusRequest)

	if err != nil {
		return err
	}

	*o = UpdateRecommendationStatusRequest(varUpdateRecommendationStatusRequest)

	return err
}

type NullableUpdateRecommendationStatusRequest struct {
	value *UpdateRecommendationStatusRequest
	isSet bool
}

func (v NullableUpdateRecommendationStatusRequest) Get() *UpdateRecommendationStatusRequest {
	return v.value
}

func (v *NullableUpdateRecommendationStatusRequest) Set(val *UpdateRecommendationStatusRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateRecommendationStatusRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateRecommendationStatusRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateRecommendationStatusRequest(val *UpdateRecommendationStatusRequest) *NullableUpdateRecommendationStatusRequest {
	return &NullableUpdateRecommendationStatusRequest{value: val, isSet: true}
}

func (v NullableUpdateRecommendationStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateRecommendationStatusRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


