/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AgentConversationListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentConversationListResponse{}

// AgentConversationListResponse struct for AgentConversationListResponse
type AgentConversationListResponse struct {
	Conversations []AgentConversation `json:"conversations"`
	Total *int32 `json:"total,omitempty"`
}

type _AgentConversationListResponse AgentConversationListResponse

// NewAgentConversationListResponse instantiates a new AgentConversationListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentConversationListResponse(conversations []AgentConversation) *AgentConversationListResponse {
	this := AgentConversationListResponse{}
	this.Conversations = conversations
	return &this
}

// NewAgentConversationListResponseWithDefaults instantiates a new AgentConversationListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentConversationListResponseWithDefaults() *AgentConversationListResponse {
	this := AgentConversationListResponse{}
	return &this
}

// GetConversations returns the Conversations field value
func (o *AgentConversationListResponse) GetConversations() []AgentConversation {
	if o == nil {
		var ret []AgentConversation
		return ret
	}

	return o.Conversations
}

// GetConversationsOk returns a tuple with the Conversations field value
// and a boolean to check if the value has been set.
func (o *AgentConversationListResponse) GetConversationsOk() ([]AgentConversation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Conversations, true
}

// SetConversations sets field value
func (o *AgentConversationListResponse) SetConversations(v []AgentConversation) {
	o.Conversations = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *AgentConversationListResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentConversationListResponse) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *AgentConversationListResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *AgentConversationListResponse) SetTotal(v int32) {
	o.Total = &v
}

func (o AgentConversationListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentConversationListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["conversations"] = o.Conversations
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

func (o *AgentConversationListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"conversations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentConversationListResponse := _AgentConversationListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentConversationListResponse)

	if err != nil {
		return err
	}

	*o = AgentConversationListResponse(varAgentConversationListResponse)

	return err
}

type NullableAgentConversationListResponse struct {
	value *AgentConversationListResponse
	isSet bool
}

func (v NullableAgentConversationListResponse) Get() *AgentConversationListResponse {
	return v.value
}

func (v *NullableAgentConversationListResponse) Set(val *AgentConversationListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentConversationListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentConversationListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentConversationListResponse(val *AgentConversationListResponse) *NullableAgentConversationListResponse {
	return &NullableAgentConversationListResponse{value: val, isSet: true}
}

func (v NullableAgentConversationListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentConversationListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


