/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ShareSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShareSettings{}

// ShareSettings Public share configuration for a note. Owner-only mutation; unauthenticated readers consume `GET /public/notes/{token}` instead. 
type ShareSettings struct {
	IsPublic bool `json:"isPublic"`
	HasPassword bool `json:"hasPassword"`
	// Opaque token embedded in the public URL. Empty when `isPublic` is false. 
	ShareToken *string `json:"shareToken,omitempty"`
	// Fully-qualified public viewer URL. Computed server-side from `PUBLIC_VIEWER_BASE` (defaults to `https://spatio.app`) and the share token. Empty when the note is private. 
	ShareUrl *string `json:"shareUrl,omitempty"`
	// When the current password was set, if any.
	PasswordSetAt *time.Time `json:"passwordSetAt,omitempty"`
}

type _ShareSettings ShareSettings

// NewShareSettings instantiates a new ShareSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShareSettings(isPublic bool, hasPassword bool) *ShareSettings {
	this := ShareSettings{}
	this.IsPublic = isPublic
	this.HasPassword = hasPassword
	return &this
}

// NewShareSettingsWithDefaults instantiates a new ShareSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShareSettingsWithDefaults() *ShareSettings {
	this := ShareSettings{}
	return &this
}

// GetIsPublic returns the IsPublic field value
func (o *ShareSettings) GetIsPublic() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value
// and a boolean to check if the value has been set.
func (o *ShareSettings) GetIsPublicOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPublic, true
}

// SetIsPublic sets field value
func (o *ShareSettings) SetIsPublic(v bool) {
	o.IsPublic = v
}

// GetHasPassword returns the HasPassword field value
func (o *ShareSettings) GetHasPassword() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasPassword
}

// GetHasPasswordOk returns a tuple with the HasPassword field value
// and a boolean to check if the value has been set.
func (o *ShareSettings) GetHasPasswordOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasPassword, true
}

// SetHasPassword sets field value
func (o *ShareSettings) SetHasPassword(v bool) {
	o.HasPassword = v
}

// GetShareToken returns the ShareToken field value if set, zero value otherwise.
func (o *ShareSettings) GetShareToken() string {
	if o == nil || IsNil(o.ShareToken) {
		var ret string
		return ret
	}
	return *o.ShareToken
}

// GetShareTokenOk returns a tuple with the ShareToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareSettings) GetShareTokenOk() (*string, bool) {
	if o == nil || IsNil(o.ShareToken) {
		return nil, false
	}
	return o.ShareToken, true
}

// HasShareToken returns a boolean if a field has been set.
func (o *ShareSettings) HasShareToken() bool {
	if o != nil && !IsNil(o.ShareToken) {
		return true
	}

	return false
}

// SetShareToken gets a reference to the given string and assigns it to the ShareToken field.
func (o *ShareSettings) SetShareToken(v string) {
	o.ShareToken = &v
}

// GetShareUrl returns the ShareUrl field value if set, zero value otherwise.
func (o *ShareSettings) GetShareUrl() string {
	if o == nil || IsNil(o.ShareUrl) {
		var ret string
		return ret
	}
	return *o.ShareUrl
}

// GetShareUrlOk returns a tuple with the ShareUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareSettings) GetShareUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ShareUrl) {
		return nil, false
	}
	return o.ShareUrl, true
}

// HasShareUrl returns a boolean if a field has been set.
func (o *ShareSettings) HasShareUrl() bool {
	if o != nil && !IsNil(o.ShareUrl) {
		return true
	}

	return false
}

// SetShareUrl gets a reference to the given string and assigns it to the ShareUrl field.
func (o *ShareSettings) SetShareUrl(v string) {
	o.ShareUrl = &v
}

// GetPasswordSetAt returns the PasswordSetAt field value if set, zero value otherwise.
func (o *ShareSettings) GetPasswordSetAt() time.Time {
	if o == nil || IsNil(o.PasswordSetAt) {
		var ret time.Time
		return ret
	}
	return *o.PasswordSetAt
}

// GetPasswordSetAtOk returns a tuple with the PasswordSetAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareSettings) GetPasswordSetAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PasswordSetAt) {
		return nil, false
	}
	return o.PasswordSetAt, true
}

// HasPasswordSetAt returns a boolean if a field has been set.
func (o *ShareSettings) HasPasswordSetAt() bool {
	if o != nil && !IsNil(o.PasswordSetAt) {
		return true
	}

	return false
}

// SetPasswordSetAt gets a reference to the given time.Time and assigns it to the PasswordSetAt field.
func (o *ShareSettings) SetPasswordSetAt(v time.Time) {
	o.PasswordSetAt = &v
}

func (o ShareSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShareSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["isPublic"] = o.IsPublic
	toSerialize["hasPassword"] = o.HasPassword
	if !IsNil(o.ShareToken) {
		toSerialize["shareToken"] = o.ShareToken
	}
	if !IsNil(o.ShareUrl) {
		toSerialize["shareUrl"] = o.ShareUrl
	}
	if !IsNil(o.PasswordSetAt) {
		toSerialize["passwordSetAt"] = o.PasswordSetAt
	}
	return toSerialize, nil
}

func (o *ShareSettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isPublic",
		"hasPassword",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShareSettings := _ShareSettings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShareSettings)

	if err != nil {
		return err
	}

	*o = ShareSettings(varShareSettings)

	return err
}

type NullableShareSettings struct {
	value *ShareSettings
	isSet bool
}

func (v NullableShareSettings) Get() *ShareSettings {
	return v.value
}

func (v *NullableShareSettings) Set(val *ShareSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableShareSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableShareSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShareSettings(val *ShareSettings) *NullableShareSettings {
	return &NullableShareSettings{value: val, isSet: true}
}

func (v NullableShareSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShareSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


