/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateEventRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEventRequest{}

// CreateEventRequest struct for CreateEventRequest
type CreateEventRequest struct {
	AccountId string `json:"account_id"`
	// Specific calendar within the account; omit for the default.
	CalendarId *string `json:"calendar_id,omitempty"`
	Event SpatioEvent `json:"event"`
	// Notification policy passed through to the provider.
	SendUpdates *string `json:"send_updates,omitempty"`
	// When set, the platform will auto-attach a conference link of the matching type (`spatio`, `meet`, `zoom`, `teams`). 
	ConferenceType *string `json:"conference_type,omitempty"`
}

type _CreateEventRequest CreateEventRequest

// NewCreateEventRequest instantiates a new CreateEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEventRequest(accountId string, event SpatioEvent) *CreateEventRequest {
	this := CreateEventRequest{}
	this.AccountId = accountId
	this.Event = event
	return &this
}

// NewCreateEventRequestWithDefaults instantiates a new CreateEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEventRequestWithDefaults() *CreateEventRequest {
	this := CreateEventRequest{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *CreateEventRequest) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CreateEventRequest) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CreateEventRequest) SetAccountId(v string) {
	o.AccountId = v
}

// GetCalendarId returns the CalendarId field value if set, zero value otherwise.
func (o *CreateEventRequest) GetCalendarId() string {
	if o == nil || IsNil(o.CalendarId) {
		var ret string
		return ret
	}
	return *o.CalendarId
}

// GetCalendarIdOk returns a tuple with the CalendarId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequest) GetCalendarIdOk() (*string, bool) {
	if o == nil || IsNil(o.CalendarId) {
		return nil, false
	}
	return o.CalendarId, true
}

// HasCalendarId returns a boolean if a field has been set.
func (o *CreateEventRequest) HasCalendarId() bool {
	if o != nil && !IsNil(o.CalendarId) {
		return true
	}

	return false
}

// SetCalendarId gets a reference to the given string and assigns it to the CalendarId field.
func (o *CreateEventRequest) SetCalendarId(v string) {
	o.CalendarId = &v
}

// GetEvent returns the Event field value
func (o *CreateEventRequest) GetEvent() SpatioEvent {
	if o == nil {
		var ret SpatioEvent
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *CreateEventRequest) GetEventOk() (*SpatioEvent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *CreateEventRequest) SetEvent(v SpatioEvent) {
	o.Event = v
}

// GetSendUpdates returns the SendUpdates field value if set, zero value otherwise.
func (o *CreateEventRequest) GetSendUpdates() string {
	if o == nil || IsNil(o.SendUpdates) {
		var ret string
		return ret
	}
	return *o.SendUpdates
}

// GetSendUpdatesOk returns a tuple with the SendUpdates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequest) GetSendUpdatesOk() (*string, bool) {
	if o == nil || IsNil(o.SendUpdates) {
		return nil, false
	}
	return o.SendUpdates, true
}

// HasSendUpdates returns a boolean if a field has been set.
func (o *CreateEventRequest) HasSendUpdates() bool {
	if o != nil && !IsNil(o.SendUpdates) {
		return true
	}

	return false
}

// SetSendUpdates gets a reference to the given string and assigns it to the SendUpdates field.
func (o *CreateEventRequest) SetSendUpdates(v string) {
	o.SendUpdates = &v
}

// GetConferenceType returns the ConferenceType field value if set, zero value otherwise.
func (o *CreateEventRequest) GetConferenceType() string {
	if o == nil || IsNil(o.ConferenceType) {
		var ret string
		return ret
	}
	return *o.ConferenceType
}

// GetConferenceTypeOk returns a tuple with the ConferenceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequest) GetConferenceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ConferenceType) {
		return nil, false
	}
	return o.ConferenceType, true
}

// HasConferenceType returns a boolean if a field has been set.
func (o *CreateEventRequest) HasConferenceType() bool {
	if o != nil && !IsNil(o.ConferenceType) {
		return true
	}

	return false
}

// SetConferenceType gets a reference to the given string and assigns it to the ConferenceType field.
func (o *CreateEventRequest) SetConferenceType(v string) {
	o.ConferenceType = &v
}

func (o CreateEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEventRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	if !IsNil(o.CalendarId) {
		toSerialize["calendar_id"] = o.CalendarId
	}
	toSerialize["event"] = o.Event
	if !IsNil(o.SendUpdates) {
		toSerialize["send_updates"] = o.SendUpdates
	}
	if !IsNil(o.ConferenceType) {
		toSerialize["conference_type"] = o.ConferenceType
	}
	return toSerialize, nil
}

func (o *CreateEventRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"event",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEventRequest := _CreateEventRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateEventRequest)

	if err != nil {
		return err
	}

	*o = CreateEventRequest(varCreateEventRequest)

	return err
}

type NullableCreateEventRequest struct {
	value *CreateEventRequest
	isSet bool
}

func (v NullableCreateEventRequest) Get() *CreateEventRequest {
	return v.value
}

func (v *NullableCreateEventRequest) Set(val *CreateEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEventRequest(val *CreateEventRequest) *NullableCreateEventRequest {
	return &NullableCreateEventRequest{value: val, isSet: true}
}

func (v NullableCreateEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


