/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
)

// checks if the IssueCollaborationTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IssueCollaborationTokenRequest{}

// IssueCollaborationTokenRequest struct for IssueCollaborationTokenRequest
type IssueCollaborationTokenRequest struct {
	// Optional `<type>:<id>` room identifier (e.g. `note:abc123`). When set, the JWT only authorizes this single room. 
	Room *string `json:"room,omitempty"`
}

// NewIssueCollaborationTokenRequest instantiates a new IssueCollaborationTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssueCollaborationTokenRequest() *IssueCollaborationTokenRequest {
	this := IssueCollaborationTokenRequest{}
	return &this
}

// NewIssueCollaborationTokenRequestWithDefaults instantiates a new IssueCollaborationTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssueCollaborationTokenRequestWithDefaults() *IssueCollaborationTokenRequest {
	this := IssueCollaborationTokenRequest{}
	return &this
}

// GetRoom returns the Room field value if set, zero value otherwise.
func (o *IssueCollaborationTokenRequest) GetRoom() string {
	if o == nil || IsNil(o.Room) {
		var ret string
		return ret
	}
	return *o.Room
}

// GetRoomOk returns a tuple with the Room field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssueCollaborationTokenRequest) GetRoomOk() (*string, bool) {
	if o == nil || IsNil(o.Room) {
		return nil, false
	}
	return o.Room, true
}

// HasRoom returns a boolean if a field has been set.
func (o *IssueCollaborationTokenRequest) HasRoom() bool {
	if o != nil && !IsNil(o.Room) {
		return true
	}

	return false
}

// SetRoom gets a reference to the given string and assigns it to the Room field.
func (o *IssueCollaborationTokenRequest) SetRoom(v string) {
	o.Room = &v
}

func (o IssueCollaborationTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IssueCollaborationTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Room) {
		toSerialize["room"] = o.Room
	}
	return toSerialize, nil
}

type NullableIssueCollaborationTokenRequest struct {
	value *IssueCollaborationTokenRequest
	isSet bool
}

func (v NullableIssueCollaborationTokenRequest) Get() *IssueCollaborationTokenRequest {
	return v.value
}

func (v *NullableIssueCollaborationTokenRequest) Set(val *IssueCollaborationTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIssueCollaborationTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIssueCollaborationTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssueCollaborationTokenRequest(val *IssueCollaborationTokenRequest) *NullableIssueCollaborationTokenRequest {
	return &NullableIssueCollaborationTokenRequest{value: val, isSet: true}
}

func (v NullableIssueCollaborationTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssueCollaborationTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


