/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AccountPlan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountPlan{}

// AccountPlan Subscription summary. `tier` is the canonical billing tier (uppercased: `FREE`, `PRO`, `MAX`, `ENTERPRISE`); `display_name` is the lowercase user-facing label. 
type AccountPlan struct {
	Tier string `json:"tier"`
	DisplayName string `json:"display_name"`
	// Stripe subscription state: `ACTIVE`, `TRIALING`, `PAST_DUE`, `CANCELED`, etc.
	SubscriptionStatus string `json:"subscription_status"`
	TrialEndsAt NullableTime `json:"trial_ends_at,omitempty"`
}

type _AccountPlan AccountPlan

// NewAccountPlan instantiates a new AccountPlan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountPlan(tier string, displayName string, subscriptionStatus string) *AccountPlan {
	this := AccountPlan{}
	this.Tier = tier
	this.DisplayName = displayName
	this.SubscriptionStatus = subscriptionStatus
	return &this
}

// NewAccountPlanWithDefaults instantiates a new AccountPlan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountPlanWithDefaults() *AccountPlan {
	this := AccountPlan{}
	return &this
}

// GetTier returns the Tier field value
func (o *AccountPlan) GetTier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tier
}

// GetTierOk returns a tuple with the Tier field value
// and a boolean to check if the value has been set.
func (o *AccountPlan) GetTierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tier, true
}

// SetTier sets field value
func (o *AccountPlan) SetTier(v string) {
	o.Tier = v
}

// GetDisplayName returns the DisplayName field value
func (o *AccountPlan) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *AccountPlan) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *AccountPlan) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetSubscriptionStatus returns the SubscriptionStatus field value
func (o *AccountPlan) GetSubscriptionStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubscriptionStatus
}

// GetSubscriptionStatusOk returns a tuple with the SubscriptionStatus field value
// and a boolean to check if the value has been set.
func (o *AccountPlan) GetSubscriptionStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionStatus, true
}

// SetSubscriptionStatus sets field value
func (o *AccountPlan) SetSubscriptionStatus(v string) {
	o.SubscriptionStatus = v
}

// GetTrialEndsAt returns the TrialEndsAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AccountPlan) GetTrialEndsAt() time.Time {
	if o == nil || IsNil(o.TrialEndsAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.TrialEndsAt.Get()
}

// GetTrialEndsAtOk returns a tuple with the TrialEndsAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccountPlan) GetTrialEndsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrialEndsAt.Get(), o.TrialEndsAt.IsSet()
}

// HasTrialEndsAt returns a boolean if a field has been set.
func (o *AccountPlan) HasTrialEndsAt() bool {
	if o != nil && o.TrialEndsAt.IsSet() {
		return true
	}

	return false
}

// SetTrialEndsAt gets a reference to the given NullableTime and assigns it to the TrialEndsAt field.
func (o *AccountPlan) SetTrialEndsAt(v time.Time) {
	o.TrialEndsAt.Set(&v)
}
// SetTrialEndsAtNil sets the value for TrialEndsAt to be an explicit nil
func (o *AccountPlan) SetTrialEndsAtNil() {
	o.TrialEndsAt.Set(nil)
}

// UnsetTrialEndsAt ensures that no value is present for TrialEndsAt, not even an explicit nil
func (o *AccountPlan) UnsetTrialEndsAt() {
	o.TrialEndsAt.Unset()
}

func (o AccountPlan) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountPlan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tier"] = o.Tier
	toSerialize["display_name"] = o.DisplayName
	toSerialize["subscription_status"] = o.SubscriptionStatus
	if o.TrialEndsAt.IsSet() {
		toSerialize["trial_ends_at"] = o.TrialEndsAt.Get()
	}
	return toSerialize, nil
}

func (o *AccountPlan) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tier",
		"display_name",
		"subscription_status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountPlan := _AccountPlan{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountPlan)

	if err != nil {
		return err
	}

	*o = AccountPlan(varAccountPlan)

	return err
}

type NullableAccountPlan struct {
	value *AccountPlan
	isSet bool
}

func (v NullableAccountPlan) Get() *AccountPlan {
	return v.value
}

func (v *NullableAccountPlan) Set(val *AccountPlan) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountPlan) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountPlan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountPlan(val *AccountPlan) *NullableAccountPlan {
	return &NullableAccountPlan{value: val, isSet: true}
}

func (v NullableAccountPlan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountPlan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


