/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChatActionDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatActionDefinition{}

// ChatActionDefinition One entry in `GET /actions`. Action ids are dotted (e.g. `direct-messages.send`, `channels.list`); the `executeAction` endpoint accepts the id with a free-form `params` object. 
type ChatActionDefinition struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	Platform string `json:"platform"`
	// Common values: `read`, `write`, `delete`, `manage`, `sync`.
	Category *string `json:"category,omitempty"`
	InputType *string `json:"inputType,omitempty"`
	OutputType *string `json:"outputType,omitempty"`
	// `null` when no scopes are declared (Go nil-slice).
	Scopes []string `json:"scopes,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _ChatActionDefinition ChatActionDefinition

// NewChatActionDefinition instantiates a new ChatActionDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatActionDefinition(id string, name string, platform string) *ChatActionDefinition {
	this := ChatActionDefinition{}
	this.Id = id
	this.Name = name
	this.Platform = platform
	return &this
}

// NewChatActionDefinitionWithDefaults instantiates a new ChatActionDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatActionDefinitionWithDefaults() *ChatActionDefinition {
	this := ChatActionDefinition{}
	return &this
}

// GetId returns the Id field value
func (o *ChatActionDefinition) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChatActionDefinition) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChatActionDefinition) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ChatActionDefinition) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ChatActionDefinition) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ChatActionDefinition) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ChatActionDefinition) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatActionDefinition) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ChatActionDefinition) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ChatActionDefinition) SetDescription(v string) {
	o.Description = &v
}

// GetPlatform returns the Platform field value
func (o *ChatActionDefinition) GetPlatform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *ChatActionDefinition) GetPlatformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *ChatActionDefinition) SetPlatform(v string) {
	o.Platform = v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *ChatActionDefinition) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatActionDefinition) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *ChatActionDefinition) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *ChatActionDefinition) SetCategory(v string) {
	o.Category = &v
}

// GetInputType returns the InputType field value if set, zero value otherwise.
func (o *ChatActionDefinition) GetInputType() string {
	if o == nil || IsNil(o.InputType) {
		var ret string
		return ret
	}
	return *o.InputType
}

// GetInputTypeOk returns a tuple with the InputType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatActionDefinition) GetInputTypeOk() (*string, bool) {
	if o == nil || IsNil(o.InputType) {
		return nil, false
	}
	return o.InputType, true
}

// HasInputType returns a boolean if a field has been set.
func (o *ChatActionDefinition) HasInputType() bool {
	if o != nil && !IsNil(o.InputType) {
		return true
	}

	return false
}

// SetInputType gets a reference to the given string and assigns it to the InputType field.
func (o *ChatActionDefinition) SetInputType(v string) {
	o.InputType = &v
}

// GetOutputType returns the OutputType field value if set, zero value otherwise.
func (o *ChatActionDefinition) GetOutputType() string {
	if o == nil || IsNil(o.OutputType) {
		var ret string
		return ret
	}
	return *o.OutputType
}

// GetOutputTypeOk returns a tuple with the OutputType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatActionDefinition) GetOutputTypeOk() (*string, bool) {
	if o == nil || IsNil(o.OutputType) {
		return nil, false
	}
	return o.OutputType, true
}

// HasOutputType returns a boolean if a field has been set.
func (o *ChatActionDefinition) HasOutputType() bool {
	if o != nil && !IsNil(o.OutputType) {
		return true
	}

	return false
}

// SetOutputType gets a reference to the given string and assigns it to the OutputType field.
func (o *ChatActionDefinition) SetOutputType(v string) {
	o.OutputType = &v
}

// GetScopes returns the Scopes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChatActionDefinition) GetScopes() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChatActionDefinition) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *ChatActionDefinition) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *ChatActionDefinition) SetScopes(v []string) {
	o.Scopes = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ChatActionDefinition) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatActionDefinition) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ChatActionDefinition) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *ChatActionDefinition) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o ChatActionDefinition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatActionDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["platform"] = o.Platform
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.InputType) {
		toSerialize["inputType"] = o.InputType
	}
	if !IsNil(o.OutputType) {
		toSerialize["outputType"] = o.OutputType
	}
	if o.Scopes != nil {
		toSerialize["scopes"] = o.Scopes
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *ChatActionDefinition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"platform",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChatActionDefinition := _ChatActionDefinition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChatActionDefinition)

	if err != nil {
		return err
	}

	*o = ChatActionDefinition(varChatActionDefinition)

	return err
}

type NullableChatActionDefinition struct {
	value *ChatActionDefinition
	isSet bool
}

func (v NullableChatActionDefinition) Get() *ChatActionDefinition {
	return v.value
}

func (v *NullableChatActionDefinition) Set(val *ChatActionDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableChatActionDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableChatActionDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatActionDefinition(val *ChatActionDefinition) *NullableChatActionDefinition {
	return &NullableChatActionDefinition{value: val, isSet: true}
}

func (v NullableChatActionDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatActionDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


