/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Label type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Label{}

// Label struct for Label
type Label struct {
	Id string `json:"id"`
	Name string `json:"name"`
	// Provider-specific label type. Common values: `system`, `user`. Not enumerated to avoid forcing a breaking change every time a provider adds one. 
	Type string `json:"type"`
	MessageListVisibility *string `json:"messageListVisibility,omitempty"`
	LabelListVisibility *string `json:"labelListVisibility,omitempty"`
	Color *LabelColor `json:"color,omitempty"`
}

type _Label Label

// NewLabel instantiates a new Label object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabel(id string, name string, type_ string) *Label {
	this := Label{}
	this.Id = id
	this.Name = name
	this.Type = type_
	return &this
}

// NewLabelWithDefaults instantiates a new Label object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelWithDefaults() *Label {
	this := Label{}
	return &this
}

// GetId returns the Id field value
func (o *Label) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Label) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Label) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Label) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Label) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Label) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *Label) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Label) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Label) SetType(v string) {
	o.Type = v
}

// GetMessageListVisibility returns the MessageListVisibility field value if set, zero value otherwise.
func (o *Label) GetMessageListVisibility() string {
	if o == nil || IsNil(o.MessageListVisibility) {
		var ret string
		return ret
	}
	return *o.MessageListVisibility
}

// GetMessageListVisibilityOk returns a tuple with the MessageListVisibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Label) GetMessageListVisibilityOk() (*string, bool) {
	if o == nil || IsNil(o.MessageListVisibility) {
		return nil, false
	}
	return o.MessageListVisibility, true
}

// HasMessageListVisibility returns a boolean if a field has been set.
func (o *Label) HasMessageListVisibility() bool {
	if o != nil && !IsNil(o.MessageListVisibility) {
		return true
	}

	return false
}

// SetMessageListVisibility gets a reference to the given string and assigns it to the MessageListVisibility field.
func (o *Label) SetMessageListVisibility(v string) {
	o.MessageListVisibility = &v
}

// GetLabelListVisibility returns the LabelListVisibility field value if set, zero value otherwise.
func (o *Label) GetLabelListVisibility() string {
	if o == nil || IsNil(o.LabelListVisibility) {
		var ret string
		return ret
	}
	return *o.LabelListVisibility
}

// GetLabelListVisibilityOk returns a tuple with the LabelListVisibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Label) GetLabelListVisibilityOk() (*string, bool) {
	if o == nil || IsNil(o.LabelListVisibility) {
		return nil, false
	}
	return o.LabelListVisibility, true
}

// HasLabelListVisibility returns a boolean if a field has been set.
func (o *Label) HasLabelListVisibility() bool {
	if o != nil && !IsNil(o.LabelListVisibility) {
		return true
	}

	return false
}

// SetLabelListVisibility gets a reference to the given string and assigns it to the LabelListVisibility field.
func (o *Label) SetLabelListVisibility(v string) {
	o.LabelListVisibility = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *Label) GetColor() LabelColor {
	if o == nil || IsNil(o.Color) {
		var ret LabelColor
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Label) GetColorOk() (*LabelColor, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *Label) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given LabelColor and assigns it to the Color field.
func (o *Label) SetColor(v LabelColor) {
	o.Color = &v
}

func (o Label) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Label) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	if !IsNil(o.MessageListVisibility) {
		toSerialize["messageListVisibility"] = o.MessageListVisibility
	}
	if !IsNil(o.LabelListVisibility) {
		toSerialize["labelListVisibility"] = o.LabelListVisibility
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	return toSerialize, nil
}

func (o *Label) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLabel := _Label{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLabel)

	if err != nil {
		return err
	}

	*o = Label(varLabel)

	return err
}

type NullableLabel struct {
	value *Label
	isSet bool
}

func (v NullableLabel) Get() *Label {
	return v.value
}

func (v *NullableLabel) Set(val *Label) {
	v.value = val
	v.isSet = true
}

func (v NullableLabel) IsSet() bool {
	return v.isSet
}

func (v *NullableLabel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabel(val *Label) *NullableLabel {
	return &NullableLabel{value: val, isSet: true}
}

func (v NullableLabel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


