/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateChannelResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateChannelResponse{}

// CreateChannelResponse struct for CreateChannelResponse
type CreateChannelResponse struct {
	Channel Channel `json:"channel"`
	Provider string `json:"provider"`
}

type _CreateChannelResponse CreateChannelResponse

// NewCreateChannelResponse instantiates a new CreateChannelResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateChannelResponse(channel Channel, provider string) *CreateChannelResponse {
	this := CreateChannelResponse{}
	this.Channel = channel
	this.Provider = provider
	return &this
}

// NewCreateChannelResponseWithDefaults instantiates a new CreateChannelResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateChannelResponseWithDefaults() *CreateChannelResponse {
	this := CreateChannelResponse{}
	return &this
}

// GetChannel returns the Channel field value
func (o *CreateChannelResponse) GetChannel() Channel {
	if o == nil {
		var ret Channel
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *CreateChannelResponse) GetChannelOk() (*Channel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *CreateChannelResponse) SetChannel(v Channel) {
	o.Channel = v
}

// GetProvider returns the Provider field value
func (o *CreateChannelResponse) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *CreateChannelResponse) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *CreateChannelResponse) SetProvider(v string) {
	o.Provider = v
}

func (o CreateChannelResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateChannelResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channel"] = o.Channel
	toSerialize["provider"] = o.Provider
	return toSerialize, nil
}

func (o *CreateChannelResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channel",
		"provider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateChannelResponse := _CreateChannelResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateChannelResponse)

	if err != nil {
		return err
	}

	*o = CreateChannelResponse(varCreateChannelResponse)

	return err
}

type NullableCreateChannelResponse struct {
	value *CreateChannelResponse
	isSet bool
}

func (v NullableCreateChannelResponse) Get() *CreateChannelResponse {
	return v.value
}

func (v *NullableCreateChannelResponse) Set(val *CreateChannelResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateChannelResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateChannelResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateChannelResponse(val *CreateChannelResponse) *NullableCreateChannelResponse {
	return &NullableCreateChannelResponse{value: val, isSet: true}
}

func (v NullableCreateChannelResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateChannelResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


