/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChunkedFileManifest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChunkedFileManifest{}

// ChunkedFileManifest Block-level manifest for a chunked-uploaded file. Returned by `GET /v1/files/{id}/manifest`. Only meaningful for files uploaded via the chunked path; legacy uploads return `404`. 
type ChunkedFileManifest struct {
	ManifestId string `json:"manifestId"`
	FileId string `json:"fileId"`
	FileName string `json:"fileName"`
	Version int32 `json:"version"`
	TotalSize int64 `json:"totalSize"`
	BlockCount int32 `json:"blockCount"`
	ChunkingAlgorithm *string `json:"chunkingAlgorithm,omitempty"`
	FileChecksum *string `json:"fileChecksum,omitempty"`
	Blocks []map[string]interface{} `json:"blocks,omitempty"`
}

type _ChunkedFileManifest ChunkedFileManifest

// NewChunkedFileManifest instantiates a new ChunkedFileManifest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChunkedFileManifest(manifestId string, fileId string, fileName string, version int32, totalSize int64, blockCount int32) *ChunkedFileManifest {
	this := ChunkedFileManifest{}
	this.ManifestId = manifestId
	this.FileId = fileId
	this.FileName = fileName
	this.Version = version
	this.TotalSize = totalSize
	this.BlockCount = blockCount
	return &this
}

// NewChunkedFileManifestWithDefaults instantiates a new ChunkedFileManifest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChunkedFileManifestWithDefaults() *ChunkedFileManifest {
	this := ChunkedFileManifest{}
	return &this
}

// GetManifestId returns the ManifestId field value
func (o *ChunkedFileManifest) GetManifestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ManifestId
}

// GetManifestIdOk returns a tuple with the ManifestId field value
// and a boolean to check if the value has been set.
func (o *ChunkedFileManifest) GetManifestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ManifestId, true
}

// SetManifestId sets field value
func (o *ChunkedFileManifest) SetManifestId(v string) {
	o.ManifestId = v
}

// GetFileId returns the FileId field value
func (o *ChunkedFileManifest) GetFileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value
// and a boolean to check if the value has been set.
func (o *ChunkedFileManifest) GetFileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileId, true
}

// SetFileId sets field value
func (o *ChunkedFileManifest) SetFileId(v string) {
	o.FileId = v
}

// GetFileName returns the FileName field value
func (o *ChunkedFileManifest) GetFileName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value
// and a boolean to check if the value has been set.
func (o *ChunkedFileManifest) GetFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileName, true
}

// SetFileName sets field value
func (o *ChunkedFileManifest) SetFileName(v string) {
	o.FileName = v
}

// GetVersion returns the Version field value
func (o *ChunkedFileManifest) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ChunkedFileManifest) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ChunkedFileManifest) SetVersion(v int32) {
	o.Version = v
}

// GetTotalSize returns the TotalSize field value
func (o *ChunkedFileManifest) GetTotalSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalSize
}

// GetTotalSizeOk returns a tuple with the TotalSize field value
// and a boolean to check if the value has been set.
func (o *ChunkedFileManifest) GetTotalSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalSize, true
}

// SetTotalSize sets field value
func (o *ChunkedFileManifest) SetTotalSize(v int64) {
	o.TotalSize = v
}

// GetBlockCount returns the BlockCount field value
func (o *ChunkedFileManifest) GetBlockCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BlockCount
}

// GetBlockCountOk returns a tuple with the BlockCount field value
// and a boolean to check if the value has been set.
func (o *ChunkedFileManifest) GetBlockCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockCount, true
}

// SetBlockCount sets field value
func (o *ChunkedFileManifest) SetBlockCount(v int32) {
	o.BlockCount = v
}

// GetChunkingAlgorithm returns the ChunkingAlgorithm field value if set, zero value otherwise.
func (o *ChunkedFileManifest) GetChunkingAlgorithm() string {
	if o == nil || IsNil(o.ChunkingAlgorithm) {
		var ret string
		return ret
	}
	return *o.ChunkingAlgorithm
}

// GetChunkingAlgorithmOk returns a tuple with the ChunkingAlgorithm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChunkedFileManifest) GetChunkingAlgorithmOk() (*string, bool) {
	if o == nil || IsNil(o.ChunkingAlgorithm) {
		return nil, false
	}
	return o.ChunkingAlgorithm, true
}

// HasChunkingAlgorithm returns a boolean if a field has been set.
func (o *ChunkedFileManifest) HasChunkingAlgorithm() bool {
	if o != nil && !IsNil(o.ChunkingAlgorithm) {
		return true
	}

	return false
}

// SetChunkingAlgorithm gets a reference to the given string and assigns it to the ChunkingAlgorithm field.
func (o *ChunkedFileManifest) SetChunkingAlgorithm(v string) {
	o.ChunkingAlgorithm = &v
}

// GetFileChecksum returns the FileChecksum field value if set, zero value otherwise.
func (o *ChunkedFileManifest) GetFileChecksum() string {
	if o == nil || IsNil(o.FileChecksum) {
		var ret string
		return ret
	}
	return *o.FileChecksum
}

// GetFileChecksumOk returns a tuple with the FileChecksum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChunkedFileManifest) GetFileChecksumOk() (*string, bool) {
	if o == nil || IsNil(o.FileChecksum) {
		return nil, false
	}
	return o.FileChecksum, true
}

// HasFileChecksum returns a boolean if a field has been set.
func (o *ChunkedFileManifest) HasFileChecksum() bool {
	if o != nil && !IsNil(o.FileChecksum) {
		return true
	}

	return false
}

// SetFileChecksum gets a reference to the given string and assigns it to the FileChecksum field.
func (o *ChunkedFileManifest) SetFileChecksum(v string) {
	o.FileChecksum = &v
}

// GetBlocks returns the Blocks field value if set, zero value otherwise.
func (o *ChunkedFileManifest) GetBlocks() []map[string]interface{} {
	if o == nil || IsNil(o.Blocks) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Blocks
}

// GetBlocksOk returns a tuple with the Blocks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChunkedFileManifest) GetBlocksOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Blocks) {
		return nil, false
	}
	return o.Blocks, true
}

// HasBlocks returns a boolean if a field has been set.
func (o *ChunkedFileManifest) HasBlocks() bool {
	if o != nil && !IsNil(o.Blocks) {
		return true
	}

	return false
}

// SetBlocks gets a reference to the given []map[string]interface{} and assigns it to the Blocks field.
func (o *ChunkedFileManifest) SetBlocks(v []map[string]interface{}) {
	o.Blocks = v
}

func (o ChunkedFileManifest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChunkedFileManifest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["manifestId"] = o.ManifestId
	toSerialize["fileId"] = o.FileId
	toSerialize["fileName"] = o.FileName
	toSerialize["version"] = o.Version
	toSerialize["totalSize"] = o.TotalSize
	toSerialize["blockCount"] = o.BlockCount
	if !IsNil(o.ChunkingAlgorithm) {
		toSerialize["chunkingAlgorithm"] = o.ChunkingAlgorithm
	}
	if !IsNil(o.FileChecksum) {
		toSerialize["fileChecksum"] = o.FileChecksum
	}
	if !IsNil(o.Blocks) {
		toSerialize["blocks"] = o.Blocks
	}
	return toSerialize, nil
}

func (o *ChunkedFileManifest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"manifestId",
		"fileId",
		"fileName",
		"version",
		"totalSize",
		"blockCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChunkedFileManifest := _ChunkedFileManifest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChunkedFileManifest)

	if err != nil {
		return err
	}

	*o = ChunkedFileManifest(varChunkedFileManifest)

	return err
}

type NullableChunkedFileManifest struct {
	value *ChunkedFileManifest
	isSet bool
}

func (v NullableChunkedFileManifest) Get() *ChunkedFileManifest {
	return v.value
}

func (v *NullableChunkedFileManifest) Set(val *ChunkedFileManifest) {
	v.value = val
	v.isSet = true
}

func (v NullableChunkedFileManifest) IsSet() bool {
	return v.isSet
}

func (v *NullableChunkedFileManifest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChunkedFileManifest(val *ChunkedFileManifest) *NullableChunkedFileManifest {
	return &NullableChunkedFileManifest{value: val, isSet: true}
}

func (v NullableChunkedFileManifest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChunkedFileManifest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


