/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrganizationWorkspacesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationWorkspacesInner{}

// OrganizationWorkspacesInner struct for OrganizationWorkspacesInner
type OrganizationWorkspacesInner struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type _OrganizationWorkspacesInner OrganizationWorkspacesInner

// NewOrganizationWorkspacesInner instantiates a new OrganizationWorkspacesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationWorkspacesInner(id string, name string, slug string) *OrganizationWorkspacesInner {
	this := OrganizationWorkspacesInner{}
	this.Id = id
	this.Name = name
	this.Slug = slug
	return &this
}

// NewOrganizationWorkspacesInnerWithDefaults instantiates a new OrganizationWorkspacesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationWorkspacesInnerWithDefaults() *OrganizationWorkspacesInner {
	this := OrganizationWorkspacesInner{}
	return &this
}

// GetId returns the Id field value
func (o *OrganizationWorkspacesInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrganizationWorkspacesInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrganizationWorkspacesInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *OrganizationWorkspacesInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OrganizationWorkspacesInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OrganizationWorkspacesInner) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *OrganizationWorkspacesInner) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *OrganizationWorkspacesInner) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *OrganizationWorkspacesInner) SetSlug(v string) {
	o.Slug = v
}

func (o OrganizationWorkspacesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationWorkspacesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["slug"] = o.Slug
	return toSerialize, nil
}

func (o *OrganizationWorkspacesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"slug",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationWorkspacesInner := _OrganizationWorkspacesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationWorkspacesInner)

	if err != nil {
		return err
	}

	*o = OrganizationWorkspacesInner(varOrganizationWorkspacesInner)

	return err
}

type NullableOrganizationWorkspacesInner struct {
	value *OrganizationWorkspacesInner
	isSet bool
}

func (v NullableOrganizationWorkspacesInner) Get() *OrganizationWorkspacesInner {
	return v.value
}

func (v *NullableOrganizationWorkspacesInner) Set(val *OrganizationWorkspacesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationWorkspacesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationWorkspacesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationWorkspacesInner(val *OrganizationWorkspacesInner) *NullableOrganizationWorkspacesInner {
	return &NullableOrganizationWorkspacesInner{value: val, isSet: true}
}

func (v NullableOrganizationWorkspacesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationWorkspacesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


