/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExportPDFRequestRasterizedSlidesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExportPDFRequestRasterizedSlidesInner{}

// ExportPDFRequestRasterizedSlidesInner struct for ExportPDFRequestRasterizedSlidesInner
type ExportPDFRequestRasterizedSlidesInner struct {
	SlideId string `json:"slideId"`
	// Base64-encoded PNG.
	Png string `json:"png"`
}

type _ExportPDFRequestRasterizedSlidesInner ExportPDFRequestRasterizedSlidesInner

// NewExportPDFRequestRasterizedSlidesInner instantiates a new ExportPDFRequestRasterizedSlidesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExportPDFRequestRasterizedSlidesInner(slideId string, png string) *ExportPDFRequestRasterizedSlidesInner {
	this := ExportPDFRequestRasterizedSlidesInner{}
	this.SlideId = slideId
	this.Png = png
	return &this
}

// NewExportPDFRequestRasterizedSlidesInnerWithDefaults instantiates a new ExportPDFRequestRasterizedSlidesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExportPDFRequestRasterizedSlidesInnerWithDefaults() *ExportPDFRequestRasterizedSlidesInner {
	this := ExportPDFRequestRasterizedSlidesInner{}
	return &this
}

// GetSlideId returns the SlideId field value
func (o *ExportPDFRequestRasterizedSlidesInner) GetSlideId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SlideId
}

// GetSlideIdOk returns a tuple with the SlideId field value
// and a boolean to check if the value has been set.
func (o *ExportPDFRequestRasterizedSlidesInner) GetSlideIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SlideId, true
}

// SetSlideId sets field value
func (o *ExportPDFRequestRasterizedSlidesInner) SetSlideId(v string) {
	o.SlideId = v
}

// GetPng returns the Png field value
func (o *ExportPDFRequestRasterizedSlidesInner) GetPng() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Png
}

// GetPngOk returns a tuple with the Png field value
// and a boolean to check if the value has been set.
func (o *ExportPDFRequestRasterizedSlidesInner) GetPngOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Png, true
}

// SetPng sets field value
func (o *ExportPDFRequestRasterizedSlidesInner) SetPng(v string) {
	o.Png = v
}

func (o ExportPDFRequestRasterizedSlidesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExportPDFRequestRasterizedSlidesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["slideId"] = o.SlideId
	toSerialize["png"] = o.Png
	return toSerialize, nil
}

func (o *ExportPDFRequestRasterizedSlidesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"slideId",
		"png",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExportPDFRequestRasterizedSlidesInner := _ExportPDFRequestRasterizedSlidesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExportPDFRequestRasterizedSlidesInner)

	if err != nil {
		return err
	}

	*o = ExportPDFRequestRasterizedSlidesInner(varExportPDFRequestRasterizedSlidesInner)

	return err
}

type NullableExportPDFRequestRasterizedSlidesInner struct {
	value *ExportPDFRequestRasterizedSlidesInner
	isSet bool
}

func (v NullableExportPDFRequestRasterizedSlidesInner) Get() *ExportPDFRequestRasterizedSlidesInner {
	return v.value
}

func (v *NullableExportPDFRequestRasterizedSlidesInner) Set(val *ExportPDFRequestRasterizedSlidesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableExportPDFRequestRasterizedSlidesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableExportPDFRequestRasterizedSlidesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportPDFRequestRasterizedSlidesInner(val *ExportPDFRequestRasterizedSlidesInner) *NullableExportPDFRequestRasterizedSlidesInner {
	return &NullableExportPDFRequestRasterizedSlidesInner{value: val, isSet: true}
}

func (v NullableExportPDFRequestRasterizedSlidesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportPDFRequestRasterizedSlidesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


