/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SendChatMessageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendChatMessageRequest{}

// SendChatMessageRequest struct for SendChatMessageRequest
type SendChatMessageRequest struct {
	AccountId *string `json:"accountId,omitempty"`
	// Channel or DM id (provider-scoped).
	Channel string `json:"channel"`
	Text string `json:"text"`
	ThreadId *string `json:"threadId,omitempty"`
	// Provider-specific rich-message blocks.
	Blocks []map[string]interface{} `json:"blocks,omitempty"`
}

type _SendChatMessageRequest SendChatMessageRequest

// NewSendChatMessageRequest instantiates a new SendChatMessageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendChatMessageRequest(channel string, text string) *SendChatMessageRequest {
	this := SendChatMessageRequest{}
	this.Channel = channel
	this.Text = text
	return &this
}

// NewSendChatMessageRequestWithDefaults instantiates a new SendChatMessageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendChatMessageRequestWithDefaults() *SendChatMessageRequest {
	this := SendChatMessageRequest{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *SendChatMessageRequest) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendChatMessageRequest) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *SendChatMessageRequest) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *SendChatMessageRequest) SetAccountId(v string) {
	o.AccountId = &v
}

// GetChannel returns the Channel field value
func (o *SendChatMessageRequest) GetChannel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *SendChatMessageRequest) GetChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *SendChatMessageRequest) SetChannel(v string) {
	o.Channel = v
}

// GetText returns the Text field value
func (o *SendChatMessageRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *SendChatMessageRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *SendChatMessageRequest) SetText(v string) {
	o.Text = v
}

// GetThreadId returns the ThreadId field value if set, zero value otherwise.
func (o *SendChatMessageRequest) GetThreadId() string {
	if o == nil || IsNil(o.ThreadId) {
		var ret string
		return ret
	}
	return *o.ThreadId
}

// GetThreadIdOk returns a tuple with the ThreadId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendChatMessageRequest) GetThreadIdOk() (*string, bool) {
	if o == nil || IsNil(o.ThreadId) {
		return nil, false
	}
	return o.ThreadId, true
}

// HasThreadId returns a boolean if a field has been set.
func (o *SendChatMessageRequest) HasThreadId() bool {
	if o != nil && !IsNil(o.ThreadId) {
		return true
	}

	return false
}

// SetThreadId gets a reference to the given string and assigns it to the ThreadId field.
func (o *SendChatMessageRequest) SetThreadId(v string) {
	o.ThreadId = &v
}

// GetBlocks returns the Blocks field value if set, zero value otherwise.
func (o *SendChatMessageRequest) GetBlocks() []map[string]interface{} {
	if o == nil || IsNil(o.Blocks) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Blocks
}

// GetBlocksOk returns a tuple with the Blocks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendChatMessageRequest) GetBlocksOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Blocks) {
		return nil, false
	}
	return o.Blocks, true
}

// HasBlocks returns a boolean if a field has been set.
func (o *SendChatMessageRequest) HasBlocks() bool {
	if o != nil && !IsNil(o.Blocks) {
		return true
	}

	return false
}

// SetBlocks gets a reference to the given []map[string]interface{} and assigns it to the Blocks field.
func (o *SendChatMessageRequest) SetBlocks(v []map[string]interface{}) {
	o.Blocks = v
}

func (o SendChatMessageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendChatMessageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	toSerialize["channel"] = o.Channel
	toSerialize["text"] = o.Text
	if !IsNil(o.ThreadId) {
		toSerialize["threadId"] = o.ThreadId
	}
	if !IsNil(o.Blocks) {
		toSerialize["blocks"] = o.Blocks
	}
	return toSerialize, nil
}

func (o *SendChatMessageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channel",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendChatMessageRequest := _SendChatMessageRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendChatMessageRequest)

	if err != nil {
		return err
	}

	*o = SendChatMessageRequest(varSendChatMessageRequest)

	return err
}

type NullableSendChatMessageRequest struct {
	value *SendChatMessageRequest
	isSet bool
}

func (v NullableSendChatMessageRequest) Get() *SendChatMessageRequest {
	return v.value
}

func (v *NullableSendChatMessageRequest) Set(val *SendChatMessageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendChatMessageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendChatMessageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendChatMessageRequest(val *SendChatMessageRequest) *NullableSendChatMessageRequest {
	return &NullableSendChatMessageRequest{value: val, isSet: true}
}

func (v NullableSendChatMessageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendChatMessageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


