/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
)

// checks if the UpdateCommentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCommentRequest{}

// UpdateCommentRequest Either `body` (preferred) or `content` is required. 
type UpdateCommentRequest struct {
	Body *string `json:"body,omitempty"`
	Content *string `json:"content,omitempty"`
}

// NewUpdateCommentRequest instantiates a new UpdateCommentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCommentRequest() *UpdateCommentRequest {
	this := UpdateCommentRequest{}
	return &this
}

// NewUpdateCommentRequestWithDefaults instantiates a new UpdateCommentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCommentRequestWithDefaults() *UpdateCommentRequest {
	this := UpdateCommentRequest{}
	return &this
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *UpdateCommentRequest) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentRequest) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *UpdateCommentRequest) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *UpdateCommentRequest) SetBody(v string) {
	o.Body = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *UpdateCommentRequest) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCommentRequest) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *UpdateCommentRequest) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *UpdateCommentRequest) SetContent(v string) {
	o.Content = &v
}

func (o UpdateCommentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCommentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	return toSerialize, nil
}

type NullableUpdateCommentRequest struct {
	value *UpdateCommentRequest
	isSet bool
}

func (v NullableUpdateCommentRequest) Get() *UpdateCommentRequest {
	return v.value
}

func (v *NullableUpdateCommentRequest) Set(val *UpdateCommentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCommentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCommentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCommentRequest(val *UpdateCommentRequest) *NullableUpdateCommentRequest {
	return &NullableUpdateCommentRequest{value: val, isSet: true}
}

func (v NullableUpdateCommentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCommentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


