/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CalendarSyncResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalendarSyncResponse{}

// CalendarSyncResponse Returned by `POST /v1/calendar/sync`. Status code is `202` by default (sync jobs queued); `200` when called with `?wait=true` and all jobs finish within the 10-second polling budget. 
type CalendarSyncResponse struct {
	Enqueued int32 `json:"enqueued"`
	Jobs []string `json:"jobs"`
	Waited *bool `json:"waited,omitempty"`
	TimedOut *bool `json:"timed_out,omitempty"`
	Errors []map[string]interface{} `json:"errors,omitempty"`
}

type _CalendarSyncResponse CalendarSyncResponse

// NewCalendarSyncResponse instantiates a new CalendarSyncResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalendarSyncResponse(enqueued int32, jobs []string) *CalendarSyncResponse {
	this := CalendarSyncResponse{}
	this.Enqueued = enqueued
	this.Jobs = jobs
	return &this
}

// NewCalendarSyncResponseWithDefaults instantiates a new CalendarSyncResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalendarSyncResponseWithDefaults() *CalendarSyncResponse {
	this := CalendarSyncResponse{}
	return &this
}

// GetEnqueued returns the Enqueued field value
func (o *CalendarSyncResponse) GetEnqueued() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Enqueued
}

// GetEnqueuedOk returns a tuple with the Enqueued field value
// and a boolean to check if the value has been set.
func (o *CalendarSyncResponse) GetEnqueuedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enqueued, true
}

// SetEnqueued sets field value
func (o *CalendarSyncResponse) SetEnqueued(v int32) {
	o.Enqueued = v
}

// GetJobs returns the Jobs field value
func (o *CalendarSyncResponse) GetJobs() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value
// and a boolean to check if the value has been set.
func (o *CalendarSyncResponse) GetJobsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Jobs, true
}

// SetJobs sets field value
func (o *CalendarSyncResponse) SetJobs(v []string) {
	o.Jobs = v
}

// GetWaited returns the Waited field value if set, zero value otherwise.
func (o *CalendarSyncResponse) GetWaited() bool {
	if o == nil || IsNil(o.Waited) {
		var ret bool
		return ret
	}
	return *o.Waited
}

// GetWaitedOk returns a tuple with the Waited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarSyncResponse) GetWaitedOk() (*bool, bool) {
	if o == nil || IsNil(o.Waited) {
		return nil, false
	}
	return o.Waited, true
}

// HasWaited returns a boolean if a field has been set.
func (o *CalendarSyncResponse) HasWaited() bool {
	if o != nil && !IsNil(o.Waited) {
		return true
	}

	return false
}

// SetWaited gets a reference to the given bool and assigns it to the Waited field.
func (o *CalendarSyncResponse) SetWaited(v bool) {
	o.Waited = &v
}

// GetTimedOut returns the TimedOut field value if set, zero value otherwise.
func (o *CalendarSyncResponse) GetTimedOut() bool {
	if o == nil || IsNil(o.TimedOut) {
		var ret bool
		return ret
	}
	return *o.TimedOut
}

// GetTimedOutOk returns a tuple with the TimedOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarSyncResponse) GetTimedOutOk() (*bool, bool) {
	if o == nil || IsNil(o.TimedOut) {
		return nil, false
	}
	return o.TimedOut, true
}

// HasTimedOut returns a boolean if a field has been set.
func (o *CalendarSyncResponse) HasTimedOut() bool {
	if o != nil && !IsNil(o.TimedOut) {
		return true
	}

	return false
}

// SetTimedOut gets a reference to the given bool and assigns it to the TimedOut field.
func (o *CalendarSyncResponse) SetTimedOut(v bool) {
	o.TimedOut = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *CalendarSyncResponse) GetErrors() []map[string]interface{} {
	if o == nil || IsNil(o.Errors) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarSyncResponse) GetErrorsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *CalendarSyncResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []map[string]interface{} and assigns it to the Errors field.
func (o *CalendarSyncResponse) SetErrors(v []map[string]interface{}) {
	o.Errors = v
}

func (o CalendarSyncResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalendarSyncResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enqueued"] = o.Enqueued
	toSerialize["jobs"] = o.Jobs
	if !IsNil(o.Waited) {
		toSerialize["waited"] = o.Waited
	}
	if !IsNil(o.TimedOut) {
		toSerialize["timed_out"] = o.TimedOut
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *CalendarSyncResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enqueued",
		"jobs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCalendarSyncResponse := _CalendarSyncResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCalendarSyncResponse)

	if err != nil {
		return err
	}

	*o = CalendarSyncResponse(varCalendarSyncResponse)

	return err
}

type NullableCalendarSyncResponse struct {
	value *CalendarSyncResponse
	isSet bool
}

func (v NullableCalendarSyncResponse) Get() *CalendarSyncResponse {
	return v.value
}

func (v *NullableCalendarSyncResponse) Set(val *CalendarSyncResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCalendarSyncResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCalendarSyncResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalendarSyncResponse(val *CalendarSyncResponse) *NullableCalendarSyncResponse {
	return &NullableCalendarSyncResponse{value: val, isSet: true}
}

func (v NullableCalendarSyncResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalendarSyncResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


