/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace — notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) and use HTTPS.  This specification is generated from the platform-service Go source on every push to `main`. The spec — not hand-written documentation — is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"time"
)

// checks if the FederatedSearch200ResponseItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FederatedSearch200ResponseItemsInner{}

// FederatedSearch200ResponseItemsInner struct for FederatedSearch200ResponseItemsInner
type FederatedSearch200ResponseItemsInner struct {
	Id *string `json:"id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	Platform *string `json:"platform,omitempty"`
	ProviderId *string `json:"provider_id,omitempty"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Snippet *string `json:"snippet,omitempty"`
	Author *string `json:"author,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Score *float32 `json:"score,omitempty"`
}

// NewFederatedSearch200ResponseItemsInner instantiates a new FederatedSearch200ResponseItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFederatedSearch200ResponseItemsInner() *FederatedSearch200ResponseItemsInner {
	this := FederatedSearch200ResponseItemsInner{}
	return &this
}

// NewFederatedSearch200ResponseItemsInnerWithDefaults instantiates a new FederatedSearch200ResponseItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFederatedSearch200ResponseItemsInnerWithDefaults() *FederatedSearch200ResponseItemsInner {
	this := FederatedSearch200ResponseItemsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FederatedSearch200ResponseItemsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederatedSearch200ResponseItemsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FederatedSearch200ResponseItemsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FederatedSearch200ResponseItemsInner) SetId(v string) {
	o.Id = &v
}

// GetEntityType returns the EntityType field value if set, zero value otherwise.
func (o *FederatedSearch200ResponseItemsInner) GetEntityType() string {
	if o == nil || IsNil(o.EntityType) {
		var ret string
		return ret
	}
	return *o.EntityType
}

// GetEntityTypeOk returns a tuple with the EntityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederatedSearch200ResponseItemsInner) GetEntityTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EntityType) {
		return nil, false
	}
	return o.EntityType, true
}

// HasEntityType returns a boolean if a field has been set.
func (o *FederatedSearch200ResponseItemsInner) HasEntityType() bool {
	if o != nil && !IsNil(o.EntityType) {
		return true
	}

	return false
}

// SetEntityType gets a reference to the given string and assigns it to the EntityType field.
func (o *FederatedSearch200ResponseItemsInner) SetEntityType(v string) {
	o.EntityType = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *FederatedSearch200ResponseItemsInner) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederatedSearch200ResponseItemsInner) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *FederatedSearch200ResponseItemsInner) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *FederatedSearch200ResponseItemsInner) SetPlatform(v string) {
	o.Platform = &v
}

// GetProviderId returns the ProviderId field value if set, zero value otherwise.
func (o *FederatedSearch200ResponseItemsInner) GetProviderId() string {
	if o == nil || IsNil(o.ProviderId) {
		var ret string
		return ret
	}
	return *o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederatedSearch200ResponseItemsInner) GetProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderId) {
		return nil, false
	}
	return o.ProviderId, true
}

// HasProviderId returns a boolean if a field has been set.
func (o *FederatedSearch200ResponseItemsInner) HasProviderId() bool {
	if o != nil && !IsNil(o.ProviderId) {
		return true
	}

	return false
}

// SetProviderId gets a reference to the given string and assigns it to the ProviderId field.
func (o *FederatedSearch200ResponseItemsInner) SetProviderId(v string) {
	o.ProviderId = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *FederatedSearch200ResponseItemsInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederatedSearch200ResponseItemsInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *FederatedSearch200ResponseItemsInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *FederatedSearch200ResponseItemsInner) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *FederatedSearch200ResponseItemsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederatedSearch200ResponseItemsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *FederatedSearch200ResponseItemsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *FederatedSearch200ResponseItemsInner) SetDescription(v string) {
	o.Description = &v
}

// GetSnippet returns the Snippet field value if set, zero value otherwise.
func (o *FederatedSearch200ResponseItemsInner) GetSnippet() string {
	if o == nil || IsNil(o.Snippet) {
		var ret string
		return ret
	}
	return *o.Snippet
}

// GetSnippetOk returns a tuple with the Snippet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederatedSearch200ResponseItemsInner) GetSnippetOk() (*string, bool) {
	if o == nil || IsNil(o.Snippet) {
		return nil, false
	}
	return o.Snippet, true
}

// HasSnippet returns a boolean if a field has been set.
func (o *FederatedSearch200ResponseItemsInner) HasSnippet() bool {
	if o != nil && !IsNil(o.Snippet) {
		return true
	}

	return false
}

// SetSnippet gets a reference to the given string and assigns it to the Snippet field.
func (o *FederatedSearch200ResponseItemsInner) SetSnippet(v string) {
	o.Snippet = &v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *FederatedSearch200ResponseItemsInner) GetAuthor() string {
	if o == nil || IsNil(o.Author) {
		var ret string
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederatedSearch200ResponseItemsInner) GetAuthorOk() (*string, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *FederatedSearch200ResponseItemsInner) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given string and assigns it to the Author field.
func (o *FederatedSearch200ResponseItemsInner) SetAuthor(v string) {
	o.Author = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *FederatedSearch200ResponseItemsInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederatedSearch200ResponseItemsInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *FederatedSearch200ResponseItemsInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *FederatedSearch200ResponseItemsInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *FederatedSearch200ResponseItemsInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederatedSearch200ResponseItemsInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *FederatedSearch200ResponseItemsInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *FederatedSearch200ResponseItemsInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *FederatedSearch200ResponseItemsInner) GetScore() float32 {
	if o == nil || IsNil(o.Score) {
		var ret float32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederatedSearch200ResponseItemsInner) GetScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *FederatedSearch200ResponseItemsInner) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float32 and assigns it to the Score field.
func (o *FederatedSearch200ResponseItemsInner) SetScore(v float32) {
	o.Score = &v
}

func (o FederatedSearch200ResponseItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FederatedSearch200ResponseItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.EntityType) {
		toSerialize["entity_type"] = o.EntityType
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	if !IsNil(o.ProviderId) {
		toSerialize["provider_id"] = o.ProviderId
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Snippet) {
		toSerialize["snippet"] = o.Snippet
	}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	return toSerialize, nil
}

type NullableFederatedSearch200ResponseItemsInner struct {
	value *FederatedSearch200ResponseItemsInner
	isSet bool
}

func (v NullableFederatedSearch200ResponseItemsInner) Get() *FederatedSearch200ResponseItemsInner {
	return v.value
}

func (v *NullableFederatedSearch200ResponseItemsInner) Set(val *FederatedSearch200ResponseItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFederatedSearch200ResponseItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFederatedSearch200ResponseItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFederatedSearch200ResponseItemsInner(val *FederatedSearch200ResponseItemsInner) *NullableFederatedSearch200ResponseItemsInner {
	return &NullableFederatedSearch200ResponseItemsInner{value: val, isSet: true}
}

func (v NullableFederatedSearch200ResponseItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFederatedSearch200ResponseItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


