/*
SpatioAPI

The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

API version: v1
Contact: hello@spatio.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spatio

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Comment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Comment{}

// Comment Threaded comment on a note. Top-level comments have `parentCommentId: null`; replies set it to the parent comment's id. `blockId` anchors the comment to a specific block; comments without a `blockId` are note-level (\"general\") comments. 
type Comment struct {
	Id string `json:"id"`
	NoteId string `json:"noteId"`
	ParentCommentId NullableString `json:"parentCommentId,omitempty"`
	BlockId NullableString `json:"blockId,omitempty"`
	Body string `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Author CommentAuthor `json:"author"`
}

type _Comment Comment

// NewComment instantiates a new Comment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComment(id string, noteId string, body string, createdAt time.Time, updatedAt time.Time, author CommentAuthor) *Comment {
	this := Comment{}
	this.Id = id
	this.NoteId = noteId
	this.Body = body
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Author = author
	return &this
}

// NewCommentWithDefaults instantiates a new Comment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommentWithDefaults() *Comment {
	this := Comment{}
	return &this
}

// GetId returns the Id field value
func (o *Comment) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Comment) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Comment) SetId(v string) {
	o.Id = v
}

// GetNoteId returns the NoteId field value
func (o *Comment) GetNoteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NoteId
}

// GetNoteIdOk returns a tuple with the NoteId field value
// and a boolean to check if the value has been set.
func (o *Comment) GetNoteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NoteId, true
}

// SetNoteId sets field value
func (o *Comment) SetNoteId(v string) {
	o.NoteId = v
}

// GetParentCommentId returns the ParentCommentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Comment) GetParentCommentId() string {
	if o == nil || IsNil(o.ParentCommentId.Get()) {
		var ret string
		return ret
	}
	return *o.ParentCommentId.Get()
}

// GetParentCommentIdOk returns a tuple with the ParentCommentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Comment) GetParentCommentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentCommentId.Get(), o.ParentCommentId.IsSet()
}

// HasParentCommentId returns a boolean if a field has been set.
func (o *Comment) HasParentCommentId() bool {
	if o != nil && o.ParentCommentId.IsSet() {
		return true
	}

	return false
}

// SetParentCommentId gets a reference to the given NullableString and assigns it to the ParentCommentId field.
func (o *Comment) SetParentCommentId(v string) {
	o.ParentCommentId.Set(&v)
}
// SetParentCommentIdNil sets the value for ParentCommentId to be an explicit nil
func (o *Comment) SetParentCommentIdNil() {
	o.ParentCommentId.Set(nil)
}

// UnsetParentCommentId ensures that no value is present for ParentCommentId, not even an explicit nil
func (o *Comment) UnsetParentCommentId() {
	o.ParentCommentId.Unset()
}

// GetBlockId returns the BlockId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Comment) GetBlockId() string {
	if o == nil || IsNil(o.BlockId.Get()) {
		var ret string
		return ret
	}
	return *o.BlockId.Get()
}

// GetBlockIdOk returns a tuple with the BlockId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Comment) GetBlockIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BlockId.Get(), o.BlockId.IsSet()
}

// HasBlockId returns a boolean if a field has been set.
func (o *Comment) HasBlockId() bool {
	if o != nil && o.BlockId.IsSet() {
		return true
	}

	return false
}

// SetBlockId gets a reference to the given NullableString and assigns it to the BlockId field.
func (o *Comment) SetBlockId(v string) {
	o.BlockId.Set(&v)
}
// SetBlockIdNil sets the value for BlockId to be an explicit nil
func (o *Comment) SetBlockIdNil() {
	o.BlockId.Set(nil)
}

// UnsetBlockId ensures that no value is present for BlockId, not even an explicit nil
func (o *Comment) UnsetBlockId() {
	o.BlockId.Unset()
}

// GetBody returns the Body field value
func (o *Comment) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *Comment) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *Comment) SetBody(v string) {
	o.Body = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Comment) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Comment) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Comment) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Comment) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Comment) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Comment) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetAuthor returns the Author field value
func (o *Comment) GetAuthor() CommentAuthor {
	if o == nil {
		var ret CommentAuthor
		return ret
	}

	return o.Author
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
func (o *Comment) GetAuthorOk() (*CommentAuthor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Author, true
}

// SetAuthor sets field value
func (o *Comment) SetAuthor(v CommentAuthor) {
	o.Author = v
}

func (o Comment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Comment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["noteId"] = o.NoteId
	if o.ParentCommentId.IsSet() {
		toSerialize["parentCommentId"] = o.ParentCommentId.Get()
	}
	if o.BlockId.IsSet() {
		toSerialize["blockId"] = o.BlockId.Get()
	}
	toSerialize["body"] = o.Body
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["author"] = o.Author
	return toSerialize, nil
}

func (o *Comment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"noteId",
		"body",
		"createdAt",
		"updatedAt",
		"author",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComment := _Comment{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComment)

	if err != nil {
		return err
	}

	*o = Comment(varComment)

	return err
}

type NullableComment struct {
	value *Comment
	isSet bool
}

func (v NullableComment) Get() *Comment {
	return v.value
}

func (v *NullableComment) Set(val *Comment) {
	v.value = val
	v.isSet = true
}

func (v NullableComment) IsSet() bool {
	return v.isSet
}

func (v *NullableComment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComment(val *Comment) *NullableComment {
	return &NullableComment{value: val, isSet: true}
}

func (v NullableComment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


